### ISSUE TITLE
Add a License to your repo (if you want to)

### ISSUE THREAD

**Issue by simonlegeek** [foxpass/tinyproxy-datadog-metrics#2]
Hi,

We are interested in the work you did for monitoring Tinyproxy with Datadog, but are reluctant to use it since no Licence is provided with it. Would you consider an MIT ou Apache2 license to allow the community to reuse your work?

**Comment by aren** [comment]
Yep! Added MIT license.

**Comment by simonlegeek** [comment]
Much appreciated!
